import React, { useContext, useState, useEffect } from "react";
import axios from "axios";
import InputField from "../common-styling/textarea";
import Buttons from "../common-styling/button";
import Lists from "../common-styling/list";
import { Divider } from "../../node_modules/semantic-ui-react";
import Image from "../common-styling/image";
import image from "../shopping-list.svg";
import { CredentialsContext } from "../components/app";
import Card from "react-bootstrap/Card";
import Button from "react-bootstrap/Button";
